server:
  port: 8080
  servlet:
      context-path: /
spring:
  datasource:
    username: root
    password: dongcheng
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone = Asia/Shanghai
#    ?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver